// ⚠️  This file is auto-generated by FlutterFire CLI.
// Run the command below to regenerate it for your Firebase project:
//
//   flutterfire configure --project=sarian-supplier
//
// DO NOT edit this file manually.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions not configured for ${defaultTargetPlatform.name}. '
          'Run: flutterfire configure --project=sarian-supplier',
        );
    }
  }

  // TODO: Replace with values generated by:
  //   flutterfire configure --project=sarian-supplier
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY',
    appId: 'YOUR_WEB_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'sarian-supplier',
    storageBucket: 'sarian-supplier.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_ANDROID_API_KEY',
    appId: 'YOUR_ANDROID_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'sarian-supplier',
    storageBucket: 'sarian-supplier.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: 'YOUR_IOS_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'sarian-supplier',
    storageBucket: 'sarian-supplier.firebasestorage.app',
    iosBundleId: 'com.sarianhealthcare.sarianSupplier',
  );
}
