// ⚠️  This file is auto-generated by FlutterFire CLI.
// Run the command below to regenerate it for your Firebase project:
//
//   flutterfire configure --project=sarian-supplier
//
// DO NOT edit this file manually.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions not configured for ${defaultTargetPlatform.name}. '
          'Run: flutterfire configure --project=sarian-supplier',
        );
    }
  }

  // TODO: Replace with values generated by:

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9erABucmFG2NdCLDOWS2a8-DsirlbaL4',
    appId: '1:611514833480:web:536f7c12ffc7ca1d44567d',
    messagingSenderId: '611514833480',
    projectId: 'sarian-supplier',
    authDomain: 'sarian-supplier.firebaseapp.com',
    storageBucket: 'sarian-supplier.firebasestorage.app',
    measurementId: 'G-NYFVNLEW6T',
  );

  //   flutterfire configure --project=sarian-supplier

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfST1NdDSStRIDMErk8FRad-5QMt8IIbY',
    appId: '1:611514833480:android:ebc40f4754f2438244567d',
    messagingSenderId: '611514833480',
    projectId: 'sarian-supplier',
    storageBucket: 'sarian-supplier.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsoZiELJiA79-oFrjN9Gh29eC80QYJnE8',
    appId: '1:611514833480:ios:b36196c9ce23c30244567d',
    messagingSenderId: '611514833480',
    projectId: 'sarian-supplier',
    storageBucket: 'sarian-supplier.firebasestorage.app',
    iosBundleId: 'com.sarianhealthcare.sarianSupplier',
  );

}